version: "3"

services:
  web:
    restart: unless-stopped
    container_name: web_backend
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    env_file: ./.env
    depends_on:
      - db
    environment:
      SQL_HOST: "db"
    command: bash -c "cd web && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/home/app/staticfiles
      - media_volume:/home/app/mediafiles
    expose:
      - 8000
  nginx:
    container_name: nginx
    restart: unless-stopped
    build: ./nginx
    expose:
      - 80
      - 443
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/home/app/staticfiles
      - media_volume:/home/app/mediafiles
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
  certbot:
    restart: unless-stopped
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email rezuan.dzbov@gmail.com -d managerdashboard.ru --agree-tos
  bot:
    restart: unless-stopped
    container_name: telegram_bot
    build: ./bot
    command: bash -c "cd bot && python main.py"
    depends_on:
      - nginx
    volumes:
      - media_volume:/home/app/mediafiles
  db:
    restart: unless-stopped
    container_name: postgres_db
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
      POSTGRES_DB: ${SQL_DATABASE}
      POSTGRES_PORT: ${SQL_PORT}
    ports:
      - "5432:5432"

volumes:
  static_volume:
  media_volume:
  postgres_data: