version: "3"

services:
  web:
    build: ./web
    env_file: ./.env
    restart: always
    depends_on:
      - db
    environment:
      SQL_HOST: "db"
    command: bash -c "cd web && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - 8000
    volumes:
      - static_volume:/home/app/staticfiles
      - media_volume:/home/app/mediafiles
    ports:
      - "8000:8000"
  bot:
    build: ./bot
    restart: always
    environment:
      API_URL: "http://web:8000/"
    command: bash -c "cd bot && python main.py"
    depends_on:
      - web
    volumes:
      - media_volume:/home/app/mediafiles
  db:
    restart: always
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
      POSTGRES_DB: ${SQL_DATABASE}
      POSTGRES_PORT: ${SQL_PORT}
    ports:
      - "5432:5432"
    expose:
      - 5432
  nginx:
    build: ./nginx
    ports:
      - "1337:80"
    expose:
      - 1337
    depends_on:
      - web
    volumes:
      - static_volume:/home/app/staticfiles
      - media_volume:/home/app/mediafiles

volumes:
  static_volume:
  media_volume:
  postgres_data: